config/routes.rb
Rails.application.routes.draw do

  root 'welcomes#index'

  get '/data' => 'welcomes#data'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/welcomes_controller.rb
class WelcomesController < ApplicationController
  before_action :set_welcome, only: [:show, :edit, :update, :destroy]

  def index
  end

  require 'open-uri'

  def data
    render json: JSON.parse(open("http://api.ucbcomedy.com/dcm?mode=development").read)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcomes_helper.rb
module WelcomesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Unofficial DCM schedule</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.10.2/moment.min.js' %>
  <%= csrf_meta_tags %>

  <meta property="og:title"  content="Unofficial DCM schedule" />
  <meta property="og:description" content="Unauthorized pirate version of the DCM schedule" />
  <meta property="og:image" content="https://www.dropbox.com/s/sos9ci0h8ohbv2g/Screenshot%202015-05-18%2018.39.36.png?dl=1"/>
</head>
<body>

<%= yield %>

<script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-63124936-1', 'auto');
    ga('send', 'pageview');

</script>
</body>
</html>

app/views/welcomes/_form.html.erb
<%= form_for(@welcome) do |f| %>
  <% if @welcome.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@welcome.errors.count, "error") %> prohibited this welcome from being saved:</h2>

      <ul>
      <% @welcome.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/welcomes/edit.html.erb
<h1>Editing Welcome</h1>

<%= render 'form' %>

<%= link_to 'Show', @welcome %> |
<%= link_to 'Back', welcomes_path %>

app/views/welcomes/index.html.erb
<div class="schedule-container">
    <div id="schedule" class="schedule">
        <div id="time-bar"></div>
    </div>
</div>
<div id="location-panel" class="location-panel">
</div>
<div class="header">Unofficial Del Close Marathon Schedule <input id="search-box" type="text" placeholder="search...">
</div>
<div id="master-spin"></div>
    <div class="modal fade" id="show-modal" tabindex="-1">
      <div class="modal-dialog" >
        <div class="modal-content">
            <div class="modal-body">
                <div class="modal-left">
                  <h4 class="modal-title modal-show-title"></h4>
                  <h3 class="modal-show-times"></h3>
                  <p class="modal-show-description"></p>
                  <ul class="modal-cast"></ul>
                </div>
                <div class="modal-right">
                  <img class="modal-image" src=""/>
                </div>
            </div>
        </div><!-- /.modal-content -->
      </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->

<!--TEMPLATES!-->
<script id="venue-row-template" type="text/x-handlebars-template">
  <div id="venue_row_{{id}}"  class="venue-row" data-venue-id="{{id}}">
  </div>
</script>

<script id="location-template" type="text/x-handlebars-template"><div class="location" data-venue-id="{{id}}">{{short_name}}</div></script>

<script id="hour-template" type="text/x-handlebars-template"><div class="hour-marker" style="left:{{offset}}px; width:{{width}}px">{{hour}}</div></script>

<script id="show-template" type="text/x-handlebars-template">
  <div class="show" data-performance-id="{{perf.id}}" data-show-id="{{show.id}}" data-start-time="{{starttime}}" data-end-time="{{endtime}}" style="left:{{offset}}px; width:{{width}}px">
    <div class="show-title">{{show.show_name}}</div>
    <div class="show-time">{{start}}-{{end}}</div>
  </div>
</script>

app/views/welcomes/new.html.erb
<h1>New Welcome</h1>

<%= render 'form' %>

<%= link_to 'Back', welcomes_path %>

app/views/welcomes/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_welcome_path(@welcome) %> |
<%= link_to 'Back', welcomes_path %>